"""Initial schema: donors, users, blood requests, donations, notifications, blocklist

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-07

Written by hand rather than autogenerated. Alembic does not diff check constraints, and
this schema leans on them for two invariants that matter: a request's status must agree
with its unit arithmetic, and a notification's response timestamp must agree with its
responded flag. Autogeneration would also have created each enum type implicitly at the
first table that references it, which fails for the enums used by more than one table.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


BLOOD_GROUPS = ("A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-")
SEXES = ("male", "female", "other")
DONOR_STATUSES = (
    "available",
    "unavailable_moved",
    "unavailable_traveling",
    "unavailable_medical",
)
REQUEST_STATUSES = ("open", "partially_fulfilled", "fulfilled")
USER_ROLES = ("admin", "donor", "patient")
NOTIFICATION_CHANNELS = ("console", "email")

ENUM_TYPES = (
    ("blood_group", BLOOD_GROUPS),
    ("sex", SEXES),
    ("donor_status", DONOR_STATUSES),
    ("request_status", REQUEST_STATUSES),
    ("user_role", USER_ROLES),
    ("notification_channel", NOTIFICATION_CHANNELS),
)


def _enum(name: str) -> postgresql.ENUM:
    """Reference an enum type that this migration has already created."""

    return postgresql.ENUM(name=name, create_type=False)


def upgrade():
    bind = op.get_bind()

    # Enum types are created once, up front. blood_group is referenced by both donors
    # and blood_requests, so leaving creation to the column definitions would attempt to
    # create the type twice.
    for type_name, values in ENUM_TYPES:
        postgresql.ENUM(*values, name=type_name).create(bind, checkfirst=False)

    op.create_table(
        "donors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("blood_group", _enum("blood_group"), nullable=False),
        sa.Column("sex", _enum("sex"), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("place", sa.String(length=120), nullable=False),
        sa.Column("last_donation_date", sa.Date(), nullable=True),
        sa.Column(
            "status", _enum("donor_status"), server_default="available", nullable=False
        ),
        sa.Column("status_note", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("weight_kg > 0", name="ck_donors_weight_positive"),
        sa.PrimaryKeyConstraint("id", name="pk_donors"),
        sa.UniqueConstraint("phone", name="uq_donors_phone"),
    )
    op.create_index(
        "ix_donors_email_unique",
        "donors",
        ["email"],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_index(
        "ix_donors_blood_group_status_last_donation",
        "donors",
        ["blood_group", "status", "last_donation_date"],
        unique=False,
    )
    op.create_index(
        "ix_donors_place_lower", "donors", [sa.text("lower(place)")], unique=False
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("role", _enum("user_role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("donor_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(role = 'donor' AND donor_id IS NOT NULL) "
            "OR (role <> 'donor' AND donor_id IS NULL)",
            name="ck_users_donor_role_requires_donor_link",
        ),
        sa.ForeignKeyConstraint(
            ["donor_id"], ["donors.id"], name="fk_users_donor_id_donors", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.UniqueConstraint("donor_id", name="uq_users_donor_id"),
    )
    op.create_index("ix_users_role", "users", ["role"], unique=False)

    op.create_table(
        "blood_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("patient_name", sa.String(length=120), nullable=False),
        sa.Column("blood_group", _enum("blood_group"), nullable=False),
        sa.Column("hospital", sa.String(length=160), nullable=False),
        sa.Column("place", sa.String(length=120), nullable=False),
        sa.Column("contact_phone", sa.String(length=20), nullable=False),
        sa.Column("units_required", sa.Integer(), nullable=False),
        sa.Column("units_fulfilled", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("needed_by_date", sa.Date(), nullable=False),
        sa.Column("status", _enum("request_status"), server_default="open", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("units_required > 0", name="ck_blood_requests_units_required_positive"),
        sa.CheckConstraint(
            "units_fulfilled >= 0", name="ck_blood_requests_units_fulfilled_non_negative"
        ),
        sa.CheckConstraint(
            "(status = 'open' AND units_fulfilled = 0) "
            "OR (status = 'partially_fulfilled' "
            "AND units_fulfilled > 0 AND units_fulfilled < units_required) "
            "OR (status = 'fulfilled' AND units_fulfilled >= units_required)",
            name="ck_blood_requests_status_matches_units",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name="fk_blood_requests_created_by_user_id_users",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_blood_requests"),
    )
    op.create_index("ix_blood_requests_status", "blood_requests", ["status"], unique=False)
    op.create_index(
        "ix_blood_requests_blood_group_status",
        "blood_requests",
        ["blood_group", "status"],
        unique=False,
    )
    op.create_index(
        "ix_blood_requests_created_by_user_id",
        "blood_requests",
        ["created_by_user_id"],
        unique=False,
    )

    op.create_table(
        "donations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("donor_id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("units_given", sa.Integer(), nullable=False),
        sa.Column("donation_date", sa.Date(), nullable=False),
        sa.Column("recorded_by_user_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("units_given > 0", name="ck_donations_units_given_positive"),
        sa.CheckConstraint("units_given <= 10", name="ck_donations_units_given_plausible"),
        sa.ForeignKeyConstraint(
            ["donor_id"], ["donors.id"], name="fk_donations_donor_id_donors", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["blood_requests.id"],
            name="fk_donations_request_id_blood_requests",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
            name="fk_donations_recorded_by_user_id_users",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_donations"),
    )
    op.create_index("ix_donations_request_id", "donations", ["request_id"], unique=False)
    op.create_index("ix_donations_donor_id", "donations", ["donor_id"], unique=False)
    op.create_index("ix_donations_donation_date", "donations", ["donation_date"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("donor_id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("responded", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "channel", _enum("notification_channel"), server_default="console", nullable=False
        ),
        sa.Column("delivery_error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(responded = true AND response_at IS NOT NULL) "
            "OR (responded = false AND response_at IS NULL)",
            name="ck_notifications_response_at_matches_responded",
        ),
        sa.ForeignKeyConstraint(
            ["donor_id"],
            ["donors.id"],
            name="fk_notifications_donor_id_donors",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["blood_requests.id"],
            name="fk_notifications_request_id_blood_requests",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_notifications"),
        sa.UniqueConstraint("donor_id", "request_id", name="uq_notifications_donor_id_request_id"),
    )
    op.create_index(
        "ix_notifications_donor_id_sent_at", "notifications", ["donor_id", "sent_at"], unique=False
    )
    op.create_index("ix_notifications_request_id", "notifications", ["request_id"], unique=False)

    op.create_table(
        "token_blocklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "revoked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_token_blocklist_user_id_users", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_token_blocklist"),
        sa.UniqueConstraint("jti", name="uq_token_blocklist_jti"),
    )
    op.create_index("ix_token_blocklist_jti", "token_blocklist", ["jti"], unique=False)
    op.create_index("ix_token_blocklist_expires_at", "token_blocklist", ["expires_at"], unique=False)


def downgrade():
    op.drop_table("token_blocklist")
    op.drop_table("notifications")
    op.drop_table("donations")
    op.drop_table("blood_requests")
    op.drop_table("users")
    op.drop_table("donors")

    # Enum types outlive the tables that used them, so dropping the tables alone would
    # leave the types behind and make a subsequent upgrade fail on a duplicate type.
    bind = op.get_bind()
    for type_name, _values in reversed(ENUM_TYPES):
        postgresql.ENUM(name=type_name).drop(bind, checkfirst=False)
